"""initial schema

Revision ID: 1f6e59ce8b17
Revises:
Create Date: 2026-07-10 14:10:36.887481

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f6e59ce8b17'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# RN-06 — AuditLog is append-only; UPDATE/DELETE are rejected by the database itself,
# not just revoked application-side, so no code path (including a future bug) can alter history.
_AUDIT_LOG_IMMUTABLE_FN = """
CREATE OR REPLACE FUNCTION audit_log_immutable() RETURNS trigger AS $$
BEGIN
    -- ERRCODE 23001 (restrict_violation, integrity-constraint-violation class) so this
    -- surfaces as IntegrityError to SQLAlchemy/asyncpg callers, like the other RN-01/02 checks.
    RAISE EXCEPTION 'audit_log is append-only: % is not permitted', TG_OP
        USING ERRCODE = '23001';
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # citext powers User.email (case-insensitive unique local login identifier).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch')),
    sa.UniqueConstraint('batch_number', name=op.f('uq_batch_batch_number'))
    )
    op.create_table('model_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('weights_path', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_version')),
    sa.UniqueConstraint('version', name=op.f('uq_model_version_version'))
    )
    op.create_index('ix_model_version_single_active', 'model_version', ['is_active'], unique=True, postgresql_where='is_active = true')
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], name=op.f('fk_audit_log_actor_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('board',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_number', sa.String(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name=op.f('fk_board_batch_id_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board')),
    sa.UniqueConstraint('batch_id', 'board_number', name=op.f('uq_board_batch_id'))
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name=op.f('fk_system_config_updated_by_user')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_config'))
    )
    op.create_table('inspection_image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('watch_folder', 'directory_scan', 'manual_import', name='image_source', native_enum=False), nullable=False),
    sa.Column('original_path', sa.String(), nullable=False),
    sa.Column('annotated_path', sa.String(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'DETECTED', 'ANALYZING', 'COMPLETED', 'FAILED', name='image_status', native_enum=False), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('fk_inspection_image_board_id_board')),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_inspection_image_created_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_image'))
    )
    op.create_table('analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'NEEDS_HUMAN_REVIEW', name='analysis_status', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('knowledge_base', 'agents', name='analysis_source', native_enum=False), nullable=False),
    sa.Column('per_defect', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executive_summary', sa.String(), nullable=True),
    sa.Column('disposition_recommendation', sa.Enum('approve', 'rework', 'discard', name='disposition_recommendation', native_enum=False), nullable=True),
    sa.Column('severity_max', sa.Enum('low', 'medium', 'high', 'critical', name='severity', native_enum=False), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'VALIDATED', 'REJECTED', name='analysis_review_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_image.id'], name=op.f('fk_analysis_image_id_inspection_image')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis')),
    sa.UniqueConstraint('image_id', name=op.f('uq_analysis_image_id'))
    )
    op.create_table('detection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('defect_type', sa.Enum('missing_hole', 'mouse_bite', 'open_circuit', 'short', 'spur', 'spurious_copper', name='defect_type', native_enum=False), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_reported', sa.Boolean(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('review', sa.Enum('unreviewed', 'confirmed', 'false_positive', name='detection_review', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("(bbox ? 'x1') AND (bbox ? 'y1') AND (bbox ? 'x2') AND (bbox ? 'y2') AND (bbox->>'x1')::numeric >= 0 AND (bbox->>'y1')::numeric >= 0 AND (bbox->>'x2')::numeric <= 1 AND (bbox->>'y2')::numeric <= 1 AND (bbox->>'x1')::numeric < (bbox->>'x2')::numeric AND (bbox->>'y1')::numeric < (bbox->>'y2')::numeric", name=op.f('ck_detection_bbox_normalized_and_ordered')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_detection_confidence_range')),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_image.id'], name=op.f('fk_detection_image_id_inspection_image'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], name=op.f('fk_detection_model_version_id_model_version')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_detection_reviewed_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection'))
    )
    # ### end Alembic commands ###

    op.execute(_AUDIT_LOG_IMMUTABLE_FN)
    op.execute(
        "CREATE TRIGGER audit_log_immutable_trigger "
        "BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_immutable()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_log_immutable_trigger ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_immutable()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection')
    op.drop_table('analysis')
    op.drop_table('inspection_image')
    op.drop_table('system_config')
    op.drop_table('board')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_index('ix_model_version_single_active', table_name='model_version', postgresql_where='is_active = true')
    op.drop_table('model_version')
    op.drop_table('batch')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS citext")
