"""add quality alert table

Revision ID: af998a29810a
Revises: 26bfb31bdbe9
Create Date: 2026-07-17 04:09:55.270804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af998a29810a'
down_revision: Union[str, Sequence[str], None] = '26bfb31bdbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('defect_rate_batch', 'defect_rate_window', name='quality_alert_type', native_enum=False), nullable=False),
    sa.Column('scope_key', sa.String(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['user.id'], name=op.f('fk_quality_alert_acknowledged_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_alert'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_alert')
    # ### end Alembic commands ###
