"""add report table

Revision ID: d99f90ad103b
Revises: bcf4b2e3cd9f
Create Date: 2026-07-17 02:30:50.617343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd99f90ad103b'
down_revision: Union[str, Sequence[str], None] = 'bcf4b2e3cd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('individual', 'consolidated', 'executive', name='report_type', native_enum=False), nullable=False),
    sa.Column('format', sa.Enum('csv', 'xlsx', 'pdf', name='report_format', native_enum=False), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='report_status', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], name=op.f('fk_report_requested_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
